[machines.desktop]
monitors = [
  { output = "DP-3", mode = "preferred", position = "0x0", scale = "auto" },
  { output = "HDMI-A-1", mode = "preferred", position = "1366x0", scale = "auto" },
]
idle_dim_secs     = 0
idle_lock_secs    = 600
idle_suspend_secs = 0

[machines.laptop]
monitors          = [{ output = "", mode = "preferred", position = "auto", scale = "auto" }]
idle_dim_secs     = 60
idle_lock_secs    = 180
idle_suspend_secs = 600
